# Generated by Django 5.2 on 2025-09-10 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="image",
            field=models.FileField(blank=True, null=True, upload_to="note_images/"),
        ),
    ]
